data:
  source_data_path: "./dataset/church"
  target_data_path: "./dataset/haunted"
  img_size: 256

model:
  batch_size: 10
  ddpm:
    target: "model.DDPM.diffusion.Model"
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    var_type: fixedlarge
    ema_rate: 0.9
    ema: False
    resamp_with_conv: True
    initial_checkpoint: "/ckpt/CHURCH.ckpt"
  classifier:
    initial_checkpoint: "/ckpt/256x256_classifier.pt"
    train: True
  adapter:
    drop: 0.1
    dim: 16
    num_heads: 2

train:
  iteration: 300
  lr: 1e-4
  warmup_lr_rate: 0.01
  warmup_iteration_rate: 0.1
  min_lr_rate: 0.1

opt:
  betas: (0.9, 0.999)
  weight_decay: 1e-4
  clip_grad: 1.0

workers: 8
seed: 1228
log_freq: 1
save_freq: 50